### PR TITLE
modify datastream application main path

### PR DESCRIPTION
**Pull request by kayleyang**

### CODE REVIEW

**Comment by kayleyang** [comment]
pass

**Review by wolfboys — APPROVED** [review]
LGTM

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by wolfboys** [comment]
what? I don't have write access?

**Comment by tisonkun** [comment]
> what? I don't have write access?

Addressed by https://issues.apache.org/jira/browse/INFRA-24234

**Pull request closed without merging**
